name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          # 8.6 has no final release yet, this tag follows its latest pre-release
          - "8.6-rc"
          - "8.5.2"
          - "8.3.10"

    container:
      image: php:${{ matrix.php }}-cli

    steps:
      - uses: actions/checkout@v6

      - name: Build and run tests
        shell: bash
        run: |
          docker-php-ext-install sockets

          sockets_ini=$(php -i | grep -m 1 -o -E '/.*sockets\.ini' || true)
          test -z "$sockets_ini" || \
            mv -v "$sockets_ini" "$(echo "$sockets_ini" | sed -e 's/sockets.ini/0-sockets.ini/')"

          docker-php-source extract

          phpize
          ./configure --enable-ev
          make install

          echo 'extension=ev.so' > /usr/local/etc/php/conf.d/z-ev.ini

          NO_INTERACTION=1 \
            TEST_PHP_EXECUTABLE="$(which php)" \
            php run-tests.php

          docker-php-source delete

  ci:
    name: CI
    if: always()
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check matrix result
        run: |
          test '${{ needs.test.result }}' = 'success'
